apiVersion: v1
kind: ConfigMap
metadata:
  name: peaks-scheduler-config
  namespace: kube-system
data:
  config.yaml: |
    apiVersion: kubescheduler.config.k8s.io/v1
    kind: KubeSchedulerConfiguration
    schedulerName: peaks-scheduler
    clientConnection:
      kubeconfig: /etc/kubernetes/scheduler.conf
    profiles:
    - schedulerName: peaks-scheduler
      plugins:
        score:
          enabled:
            - name: NodeResourcesFit
